"""KnowledgeStage — extract structured knowledge units from text chunks.

LLM-first extraction: each chunk is sent to the configured LLM provider
with a **strict JSON schema** (see :class:`KnowledgeExtractionSchema`),
asking for an array of units with ``unit_type``, ``title``, ``content``,
``tags`` and ``confidence``.  When no LLM is available (or the provider
fails), the stage falls back to improved heuristic pattern matching.

Every produced :class:`~book_to_skills.domain.models.KnowledgeUnit`
carries provenance: ``book_id`` and ``source_book`` are filled from
``context.book`` automatically, titles are cleaned with
:func:`~book_to_skills.utils.text_utils.normalize_title`, and tags are
specific domain tags (3-5) generated by the LLM.

This stage only extracts knowledge units.  Building
:class:`~book_to_skills.domain.models.HermesSkill` objects is the job
of :class:`~book_to_skills.pipeline.skill_gen.SkillGenStage`.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from ..config import PipelineConfig
from ..domain.enums import PipelineStage, SkillStatus
from ..domain.models import HermesSkill, KnowledgeUnit, PipelineContext, TextChunk
from ..utils.text_utils import normalize_title
from .base import BaseStage

# ── Strict JSON schemas for LLM extraction ──────────────────────────


class KnowledgeUnitSchema(BaseModel):
    """One knowledge unit as returned by the LLM (validated strictly)."""

    unit_type: str = Field(default="", description="Exactly one of the requested unit types")
    title: str = Field(default="", description="Short, specific title (3-8 words)")
    content: str = Field(
        default="", description="Concrete knowledge, rule, or advice (1-3 sentences)"
    )
    tags: list[str] = Field(
        default_factory=list, description="3-5 specific domain tags, not generic words"
    )
    confidence: float = Field(default=0.8, ge=0.0, le=1.0, description="0.0-1.0")


class KnowledgeExtractionSchema(BaseModel):
    """JSON envelope for one chunk's extraction result."""

    units: list[KnowledgeUnitSchema] = Field(default_factory=list)


# Aliases for unit types the LLM may produce in a slightly different form.
# Keys are already normalized (hyphens -> underscores) via _normalize_type.
_TYPE_ALIASES: dict[str, str] = {
    "best_practices": "best_practice",
    "anti_patterns": "anti_pattern",
    "mistake": "common_mistake",
    "work_flow": "workflow",
    "workflow_steps": "workflow",
    "check_list": "checklist",
    "decisiontree": "decision_tree",
}

_SYSTEM_PROMPT = (
    "You are a precise knowledge-extraction engine for business and "
    "self-development books. Extract only concrete, high-value knowledge "
    "that is genuinely supported by the text. Never invent facts. Avoid "
    "generic filler units. Tags must be specific domain terms (3-5 per "
    "unit), never broad words like 'business' or 'marketing' alone."
)


class KnowledgeStage(BaseStage):
    """Pipeline stage that extracts KnowledgeUnits from each TextChunk.

    Uses the configured LLM provider with a strict JSON schema by
    default (much higher quality).  Falls back to regex/pattern-based
    extraction when the LLM is unconfigured or unreachable.

    Stores results in ``context.knowledge_units`` with ``book_id`` and
    ``source_book`` filled from ``context.book``.

    Example::

        stage = KnowledgeStage(config)
        context = await stage.execute(context)
        assert len(context.knowledge_units) > 0
    """

    # ── Heuristic patterns ──────────────────────────────────────────
    _SKILL_PATTERN = re.compile(
        r"(?P<title>Skill|Technique|Method|Strategy|Approach)[:\-]\s*(?P<content>.+)",
        re.IGNORECASE,
    )
    _BEST_PRACTICE_PATTERN = re.compile(
        r"(?:(?:Best\s*Practice|Pro\s*Tip|Recommendation|Guideline|Rule\s*of\s*Thumb)"
        r"[:\-]\s*(?P<content>.+))",
        re.IGNORECASE,
    )
    _ANTI_PATTERN_PATTERN = re.compile(
        r"(?:(?:Anti[\-\s]*Pattern|Common\s*Mistake|Pitfall|Avoid|Watch\s*Out)"
        r"[:\-]\s*(?P<content>.+))",
        re.IGNORECASE,
    )
    _WORKFLOW_PATTERN = re.compile(
        r"(?:Step\s+\d+|Phase|Stage|Process|Workflow)[:\-]\s*(?P<content>.+)",
        re.IGNORECASE,
    )
    _RULE_PATTERN = re.compile(
        r"(?:Rule\s+\d+|Principle|Law|Always|Never|Always\s+use|Never\s+use)"
        r"[:\-]?\s*(?P<content>.+)",
        re.IGNORECASE,
    )
    _EXAMPLE_PATTERN = re.compile(
        r"(?:Example|For\s+example|For\s+instance|e\.g\.)[:\-]?\s*(?P<content>.+)",
        re.IGNORECASE,
    )

    # Mapping from pattern to unit_type
    _PATTERN_MAP: list[tuple[re.Pattern[str], str]] = [
        (_SKILL_PATTERN, "skill"),
        (_BEST_PRACTICE_PATTERN, "best_practice"),
        (_ANTI_PATTERN_PATTERN, "anti_pattern"),
        (_WORKFLOW_PATTERN, "workflow"),
        (_RULE_PATTERN, "rule"),
        (_EXAMPLE_PATTERN, "example"),
    ]

    # Keyword stems -> tag (used only for the heuristic fallback)
    _TAG_KEYWORDS: dict[str, str] = {
        "python": "python",
        "javascript": "javascript",
        "typescript": "typescript",
        "react": "react",
        "api": "api",
        "database": "database",
        "testing": "testing",
        "deploy": "deployment",
        "security": "security",
        "performance": "performance",
        "marketing": "marketing",
        "advertis": "advertising",
        "brand": "branding",
        "seo": "seo",
        "social media": "social-media",
        "email": "email-marketing",
        "funnel": "funnels",
        "lead": "lead-generation",
        "sales": "sales",
        "negotiat": "negotiation",
        "prospect": "prospecting",
        "closing": "closing",
        "pricing": "pricing",
        "copywriting": "copywriting",
        "storytell": "storytelling",
        "persuas": "persuasion",
        "psycholog": "psychology",
        "habit": "habits",
        "productivity": "productivity",
        "discipline": "discipline",
        "mindset": "mindset",
        "finance": "finance",
        "invest": "investing",
        "budget": "budgeting",
        "entrepreneur": "entrepreneurship",
        "startup": "startups",
        "leadership": "leadership",
        "team": "teamwork",
        "hire": "hiring",
        "customer": "customers",
        "product": "product",
    }

    def __init__(self, config: PipelineConfig) -> None:
        super().__init__(config)
        self.stage = PipelineStage.KNOWLEDGE
        self._knowledge_config = config.knowledge

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    async def process(self, context: PipelineContext) -> PipelineContext:
        """Extract knowledge units from every chunk.

        Uses the configured LLM provider when available (much higher
        quality), falling back to heuristic pattern matching when the
        LLM is unreachable or unconfigured.

        Parameters
        ----------
        context : PipelineContext
            Must have ``context.chunks`` populated.

        Returns
        -------
        PipelineContext
            Context with ``knowledge_units`` appended (``book_id`` and
            ``source_book`` always filled from ``context.book``).

        Raises
        ------
        ValueError
            If no chunks exist.
        """
        if not context.chunks:
            msg = "No chunks to extract knowledge from"
            raise ValueError(msg)

        allowed_types = {t.lower() for t in self._knowledge_config.extract_types}
        min_confidence = self._knowledge_config.min_confidence
        max_per_chunk = self._knowledge_config.max_units_per_chunk

        # Try LLM-based extraction first (much higher quality)
        llm_units = await self._extract_with_llm(context, allowed_types)
        if llm_units:
            units = [u for u in llm_units if u.confidence >= min_confidence]
            all_units = units[: max_per_chunk * len(context.chunks)]
            method = "llm"
        else:
            # Fallback: heuristic pattern matching
            all_units = []
            for chunk in context.chunks:
                chunk_units = self._extract_from_chunk(chunk, allowed_types)
                chunk_units = [u for u in chunk_units if u.confidence >= min_confidence]
                all_units.extend(chunk_units[:max_per_chunk])
            method = "heuristic"

        # Fill provenance for every unit (LLM and heuristic alike)
        self._apply_book_refs(all_units, context)

        context.knowledge_units.extend(all_units)
        context.stage_results[self.stage.value] = {
            "total_units": len(all_units),
            "types_found": self._count_types(all_units),
            "method": method,
        }

        self.record_metric("total_units", len(all_units))
        return context

    # ------------------------------------------------------------------
    # LLM-based extraction (strict JSON schema)
    # ------------------------------------------------------------------

    async def _extract_with_llm(
        self,
        context: PipelineContext,
        allowed_types: set[str],
    ) -> list[KnowledgeUnit]:
        """Extract knowledge units using the configured LLM provider.

        Uses ``generate_structured`` with :class:`KnowledgeExtractionSchema`
        when the provider supports it; falls back to a plain ``generate``
        call with an explicit JSON instruction parsed via ``json.loads``.
        Returns an empty list when no LLM is available/configured so the
        caller falls back to heuristics.
        """
        try:
            from ..llm.provider_factory import get_llm_provider

            provider = get_llm_provider(self.config)
        except Exception:
            return []

        types_list = sorted(allowed_types)
        book_id, source_book = self._book_refs(context)
        all_units: list[KnowledgeUnit] = []

        for chunk in context.chunks:
            prompt = f"""Analyze the following book excerpt and extract structured knowledge from it.

Extract items of these types (only if genuinely present):
{", ".join(types_list)}

For each distinct piece of knowledge return an object with:
- "unit_type": exactly one of the allowed types above (underscored, e.g. "best_practice")
- "title": a short, specific, descriptive name (3-8 words, NOT the type name)
- "content": the concrete knowledge, rule, or advice (1-3 sentences)
- "tags": 3-5 specific domain tags (lowercase, specific — never generic like "business")
- "confidence": a float 0.0-1.0 expressing how sure you are this unit is genuine

Rules:
- Only extract high-value, concrete knowledge that is truly in the text
- No duplicate units
- If nothing valuable exists, return {{"units": []}}
- Respond with ONLY valid JSON, no markdown fences.

TEXT:
{chunk.text[:4000]}
"""
            raw_units: list[dict[str, Any]] = []
            try:
                # Preferred path: provider-native structured output
                result = await provider.generate_structured(
                    prompt,
                    KnowledgeExtractionSchema,
                    system_prompt=_SYSTEM_PROMPT,
                    temperature=0.2,
                )
                data = result.model_dump() if hasattr(result, "model_dump") else result
                raw_units = self._extract_raw_units(data)
            except Exception:
                # Fallback: explicit-JSON prompt parsed with json.loads
                try:
                    resp = await provider.generate(
                        prompt=prompt + "\n\nReturn ONLY a JSON object of the form:\n"
                        '{"units": [{"unit_type": "...", "title": "...", '
                        '"content": "...", "tags": ["..."], "confidence": 0.9}]}',
                        system_prompt=_SYSTEM_PROMPT,
                        temperature=0.2,
                        max_tokens=2000,
                        model=self.config.llm.model_small,
                    )
                except Exception:
                    continue  # this chunk falls back to heuristics
                parsed = self._parse_json_response(resp.content)
                raw_units = self._extract_raw_units(parsed)

            seen: set[tuple[str, str]] = set()
            for raw in raw_units:
                unit = self._coerce_unit(raw, chunk, allowed_types, book_id, source_book)
                if unit is None:
                    continue
                key = (unit.unit_type, unit.title)
                if key in seen:
                    continue
                seen.add(key)
                all_units.append(unit)

        return all_units

    @staticmethod
    def _extract_raw_units(parsed: Any) -> list[dict[str, Any]]:
        """Normalise a parsed JSON payload into a list of unit dicts."""
        if parsed is None:
            return []
        if isinstance(parsed, list):
            return [u for u in parsed if isinstance(u, dict)]
        if isinstance(parsed, dict):
            units = parsed.get("units")
            if isinstance(units, list):
                return [u for u in units if isinstance(u, dict)]
            # A single unit object returned directly
            if "unit_type" in parsed or "title" in parsed:
                return [parsed]
        return []

    @classmethod
    def _coerce_unit(
        cls,
        raw: dict[str, Any],
        chunk: TextChunk,
        allowed_types: set[str],
        book_id: str,
        source_book: str,
    ) -> KnowledgeUnit | None:
        """Validate + normalise one raw LLM unit into a KnowledgeUnit."""
        unit_type = cls._normalize_type(str(raw.get("unit_type", "")), allowed_types)
        if not unit_type:
            return None

        content = str(raw.get("content", "")).strip()
        if len(content) < 10:
            return None

        title = normalize_title(str(raw.get("title", "")).strip())
        if not title:
            title = normalize_title(content[:60])
        if not title:
            title = unit_type.replace("_", " ")

        try:
            confidence = float(raw.get("confidence", 0.8))
        except (TypeError, ValueError):
            confidence = 0.8
        confidence = round(min(max(confidence, 0.0), 1.0), 2)

        tags = cls._clean_tags(raw.get("tags", []))
        # Never leave a unit untagged: top up with keyword inference
        if len(tags) < 2:
            tags = list(dict.fromkeys([*tags, *cls._infer_tags(content)]))
        if not tags:
            tags = [unit_type]

        return KnowledgeUnit(
            chunk_id=chunk.id,
            book_id=book_id,
            source_book=source_book,
            unit_type=unit_type,
            title=title[:120],
            content=content[:2000],
            confidence=confidence,
            source_reference=f"chunk_{chunk.index}",
            tags=tags[:5],
            metadata={"extraction": "llm"},
        )

    @staticmethod
    def _normalize_type(raw: str, allowed_types: set[str]) -> str:
        """Map LLM type spellings onto the allowed type vocabulary."""
        t = raw.strip().lower().replace("-", "_")
        t = _TYPE_ALIASES.get(t, t)
        return t if t in allowed_types else ""

    @staticmethod
    def _clean_tags(raw: Any) -> list[str]:
        """Normalise tags to lowercase kebab tokens, max 5."""
        if isinstance(raw, str):
            raw = [t.strip() for t in re.split(r"[,\s]+", raw) if t.strip()]
        if not isinstance(raw, list):
            return []
        tags: list[str] = []
        for t in raw:
            tag = re.sub(r"[^a-z0-9]+", "-", str(t).strip().lower()).strip("-")
            if tag and len(tag) <= 30 and tag not in tags:
                tags.append(tag)
            if len(tags) >= 5:
                break
        return tags

    @staticmethod
    def _parse_json_response(raw: str) -> Any | None:
        """Best-effort JSON extraction from an LLM response."""
        text = raw.strip()
        if not text:
            return None
        # Strip markdown code fences
        fence = re.search(r"```(?:json)?\s*(.*?)```", text, re.DOTALL)
        if fence:
            text = fence.group(1).strip()
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass
        # Find the first array/object in the response
        for start, end in (("[", "]"), ("{", "}")):
            idx = text.find(start)
            if idx == -1:
                continue
            try:
                return json.loads(text[idx : text.rfind(end) + 1])
            except json.JSONDecodeError:
                continue
        # Last resort: some models emit Python-style literals (single quotes)
        import ast

        for start, end in (("{", "}"), ("[", "]")):
            idx = text.find(start)
            if idx == -1:
                continue
            try:
                return ast.literal_eval(text[idx : text.rfind(end) + 1])
            except (ValueError, SyntaxError):
                continue
        return None

    # ------------------------------------------------------------------
    # Provenance helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _book_refs(context: PipelineContext) -> tuple[str, str]:
        """Return ``(book_id, source_book)`` from the context's book."""
        if context.book:
            book_id = context.book.id or ""
            source_book = context.book.title or Path(context.book.file_path).name
            return book_id, source_book
        return "", ""

    @staticmethod
    def _apply_book_refs(units: list[KnowledgeUnit], context: PipelineContext) -> None:
        """Fill ``book_id`` / ``source_book`` on every unit."""
        book_id, source_book = KnowledgeStage._book_refs(context)
        for u in units:
            if not u.book_id:
                u.book_id = book_id
            if not u.source_book:
                u.source_book = source_book

    # ------------------------------------------------------------------
    # Legacy skill building (kept for backwards compatibility)
    #
    # NOTE: Skill generation is now the responsibility of SkillGenStage.
    # These helpers are retained so existing subclasses keep working,
    # but ``process`` no longer calls them.
    # ------------------------------------------------------------------

    def _build_skills_from_units(
        self,
        context: PipelineContext,
        units: list[KnowledgeUnit],
    ) -> None:
        """[Deprecated] Group knowledge units into HermesSkills.

        Use :class:`~book_to_skills.pipeline.skill_gen.SkillGenStage`
        instead — it produces higher-quality skills with LLM naming,
        categories, and fully populated sections.
        """
        if not units:
            return

        priority = ["skill", "best_practice", "framework", "workflow"]
        grouped: dict[str, list[KnowledgeUnit]] = {}
        for u in units:
            grouped.setdefault(u.unit_type, []).append(u)

        for unit_type in priority:
            group = grouped.pop(unit_type, None)
            if not group:
                continue
            skill = self._assemble_skill(context, unit_type, group)
            if skill:
                context.skills.append(skill)

        for unit_type, group in grouped.items():
            if not group:
                continue
            skill = self._assemble_skill(context, unit_type, group)
            if skill:
                context.skills.append(skill)

    def _assemble_skill(
        self,
        context: PipelineContext,
        unit_type: str,
        units: list[KnowledgeUnit],
    ) -> HermesSkill | None:
        """[Deprecated] Assemble a HermesSkill from a group of units."""
        if not units:
            return None

        from ..utils.text_utils import normalize_skill_name

        first = units[0]
        name = normalize_skill_name(first.title) or f"{unit_type}-{units[0].chunk_id[:6]}"

        best_practices = [u.content for u in units if u.unit_type == "best_practice"]
        pitfalls = [u.content for u in units if u.unit_type == "anti_pattern"]
        rules = [u.content for u in units if u.unit_type == "rule"]

        description = best_practices[0] if best_practices else first.content
        if rules:
            description = f"{description} {rules[0]}" if description else rules[0]

        tags = set()
        for u in units:
            tags.update(u.tags)

        book_id, source_book = self._book_refs(context)
        return HermesSkill(
            knowledge_ids=[u.id for u in units],
            book_id=book_id,
            source_book=source_book,
            name=name[:100],
            description=description[:300],
            best_practices=best_practices[:10],
            pitfalls=pitfalls[:10],
            tags=sorted(tags)[:10],
            category=self._pick_category(tags),
            status=SkillStatus.DRAFT,
            quality_score=min(1.0, len(units) / 5),
            model_used="book-to-skills-kg",
        )

    @staticmethod
    def _pick_category(tags: set[str]) -> str:
        """Map tags to a category."""
        priority = [
            ("python", "software-development"),
            ("javascript", "software-development"),
            ("api", "software-development"),
            ("database", "data"),
            ("security", "security"),
            ("testing", "quality-assurance"),
            ("deployment", "devops"),
            ("performance", "performance"),
            ("marketing", "marketing"),
            ("sales", "sales"),
            ("business", "business"),
        ]
        for tag, category in priority:
            if tag in tags:
                return category
        return "general"

    # ------------------------------------------------------------------
    # Heuristic extraction internals
    # ------------------------------------------------------------------

    def _extract_from_chunk(
        self,
        chunk: TextChunk,
        allowed_types: set[str],
    ) -> list[KnowledgeUnit]:
        """Run pattern matchers on a single chunk (heuristic fallback)."""
        units: list[KnowledgeUnit] = []
        seen_lines: set[int] = set()
        lines = chunk.text.splitlines()

        for lineno, line in enumerate(lines):
            stripped = line.strip()
            if not stripped or lineno in seen_lines:
                continue

            for pattern, unit_type in self._PATTERN_MAP:
                if unit_type not in allowed_types:
                    continue
                m = pattern.match(stripped)
                if m:
                    content = m.group("content").strip()
                    if not content or len(content) < 10:
                        continue

                    # Title from the line prefix (before colon/dash)
                    title = stripped.split(":")[0].strip() if ":" in stripped else unit_type
                    title = stripped.split("—")[0].strip() if "—" in stripped else title
                    title = normalize_title(title) or normalize_title(content[:60])

                    unit = KnowledgeUnit(
                        chunk_id=chunk.id,
                        unit_type=unit_type,
                        title=title[:120],
                        content=content,
                        confidence=self._compute_confidence(unit_type, content),
                        source_reference=f"chunk_{chunk.index}",
                        tags=self._infer_tags(content)[:5],
                        metadata={"extraction": "heuristic"},
                    )
                    units.append(unit)
                    seen_lines.add(lineno)
                    break  # first match per line

        return units

    @staticmethod
    def _compute_confidence(unit_type: str, content: str) -> float:
        """Heuristic confidence based on content length and unit type."""
        base = {"skill": 0.5, "best_practice": 0.6, "anti_pattern": 0.6}
        score = base.get(unit_type, 0.4)
        # Longer content gets a small bonus
        length_bonus = min(len(content) / 1000, 0.3)
        return round(min(score + length_bonus, 0.95), 2)

    @classmethod
    def _infer_tags(cls, content: str) -> list[str]:
        """Infer specific tags from domain keywords (heuristic fallback)."""
        tags: list[str] = []
        lower = content.lower()
        for keyword, tag in cls._TAG_KEYWORDS.items():
            if keyword in lower and tag not in tags:
                tags.append(tag)
        return tags

    @staticmethod
    def _count_types(units: list[KnowledgeUnit]) -> dict[str, int]:
        counts: dict[str, int] = {}
        for u in units:
            counts[u.unit_type] = counts.get(u.unit_type, 0) + 1
        return counts
